server:
  port: 8080

spring:
  application:
    name: member
  datasource:
    driverClassName: oracle.jdbc.OracleDriver
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.Oracle10gDialect
  main:
    allow-bean-definition-overriding: true
#  redis:
#    sentinel:
#      master:
#      nodes:

feign:
  hystrix:
    enabled: false

axon:
  serializer:
    general: xstream
  axonserver:
    servers: localhost:8124


external-api:
  mail:
    url: http://localhost:8090


logging.level.com.instagram : debug