server:
  port: 8080

spring:
  application:
    name: member
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: instagram
    password: instagram
    driverClassName: oracle.jdbc.OracleDriver
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.Oracle10gDialect
  main:
    allow-bean-definition-overriding: true


axon:
  serializer:
    general: xstream
  axonserver:
    servers: localhost:8124


logging.level.com.instagram : debug